name: 'Aws testing'
 
# The workflow should only trigger on pull requests to the main branch
on:
  workflow_dispatch:
 
# Required to get the ID Token that will be used for OIDC
permissions:
  id-token: write
  contents: read # needed for private repos to checkout
 
jobs:
  read-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
        with:
          role-to-assume: arn:aws:iam::277978271553:role/sts-lab-2-target
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "us-east-1"
 
      - run: aws sts get-caller-identity
        shell: bash

      - run: aws iam list-attached-role-policies --role-name sts-lab-2-target
        shell: bash
      
      - run: aws iam get-policy-version --policy-arn arn:aws:iam::277978271553:policy/sts_lab_2_target --version-id v1
        shell: bash  

      - run: aws secretsmanager get-secret-value --secret-id flag_sts_lab_2
        shell: bash  