name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: bash main.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "good bye from main!"
      
      - name: Check variables
        run: |
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          
          echo "github.event.comment.body: ${{ github.event.comment.body }}"
          echo "github.event.issue.body: ${{ github.event.issue.body }}"
          echo "github.event.issue.title: ${{ github.event.issue.title }}"
